package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/aronluigi/axon/pkg/gql/graph/generated"
	"github.com/aronluigi/axon/pkg/gql/graph/model"
)

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context) ([]*model.Node, error) {
	var res []*model.Node
	defaultNodes := r.DefaultNodes

	for _, n := range defaultNodes {
		res = append(res, &model.Node{
			DisplayName: n.DisplayName,
			PackageName: n.PackageName,
		})
	}

	return res, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
